from .admin_views import *
from .announcement_views import *
from .auth_views import *
from .course_views import *
from .dashboard_views import *
from .enroll_views import *
from .home_views import *
from .instructor_views import *
from .profile_views import *