# Generated by Django 5.2.6 on 2025-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
