# Generated by Django 5.2.6 on 2025-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_users_bio_users_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.FileField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
