# Generated by Django 5.2.6 on 2025-10-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_courses_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
