# Generated by Django 5.2.6 on 2025-10-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_announcements_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
