# Generated by Django 5.2.6 on 2025-10-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_announcements_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
