# Generated by Django 5.2.6 on 2025-10-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_users_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
