# Generated by Django 5.2.6 on 2025-10-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_studentprofile_major_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
    ]
