# Generated by Django 5.2.6 on 2025-10-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
