# Generated by Django 5.2.6 on 2025-10-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_instructorprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='expertise',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
